NAME = so_long

SRC_MAP = flood_fill map_check read_map
SRC_CUSTOM = get_next_line_bonus get_next_line_utils_bonus
SRC_DRAW = aux_func draw images map_draw sprites


SRC = $(addprefix $(SRCS_DIR)/,$(addsuffix .c, $(S)))
      $(addprefic $())
